# Generated by Django 5.0.1 on 2024-02-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_rename_title_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='years_with_company',
            field=models.FloatField(),
        ),
    ]
